### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by osysltd** [nelenkov/keystore-decryptor#2]
Dear developer,

First of all thank you for your time and development, awesome stuff. Trying to build the latest commit I've got an error:

`
Gradle 3.2.1
Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.8
Ant:          Apache Ant(TM) version 1.9.8 compiled on January 19 2017
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Linux 4.8.0-kali2-amd64 amd64

root@laptop:~/keystore-decryptor# gradle build.gradle -stacktrace

FAILURE: Build failed with an exception.

* Where:
Build file '/root/keystore-decryptor/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating root project 'keystore-decryptor'.
> Failed to apply plugin [class 'com.github.jengelman.gradle.plugins.shadow.ShadowBasePlugin']
   > No signature of method: org.gradle.internal.classloader.FilteringClassLoader.allowPackage() is applicable for argument types: (java.lang.String) values: [org.apache.tools.zip]
`

Maybe you know how to fix? Please advice.

Thank you.

**Comment by clviper** [comment]
@osysltd you need to ajust the plugins in the build.gradle:

Use

`plugins {
  id 'java' // or 'groovy' Must be explicitly applied
  id 'com.github.johnrengelman.shadow' version '1.2.3'
}
`
instead of:

`apply plugin: 'java'
apply plugin: 'com.github.johnrengelman.shadow'`

**Comment by osysltd** [comment]
Works great, thank you very much for the response!

**Comment by clviper** [comment]
@osysltd no problem. I was having the same problem.

**Comment by osysltd** [comment]
I've did a pull request to get rid of future concerns, you may want to merge it.
